# app/services/pdf_report_service.py
from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.pdfgen import canvas
from io import BytesIO
from datetime import datetime
from app.services.schemas import SessionData, FinalReport


def generate_pdf_from_report(session_data: SessionData, final_report: FinalReport) -> bytes:
    """
    Takes the final SessionData and FinalReport and generates a PDF using ReportLab.
    Returns the PDF content as bytes.
    """
    # Create a BytesIO buffer to hold the PDF
    buffer = BytesIO()
    
    # Create the PDF document
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=0.75*inch,
        leftMargin=0.75*inch,
        topMargin=0.75*inch,
        bottomMargin=0.75*inch
    )
    
    # Container for the 'Flowable' objects
    elements = []
    
    # Define styles
    styles = getSampleStyleSheet()
    
    # Custom styles
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=colors.HexColor('#2c3e50'),
        spaceAfter=12,
        alignment=TA_CENTER,
        fontName='Helvetica-Bold'
    )
    
    heading_style = ParagraphStyle(
        'CustomHeading',
        parent=styles['Heading2'],
        fontSize=16,
        textColor=colors.HexColor('#2c3e50'),
        spaceAfter=10,
        spaceBefore=10,
        fontName='Helvetica-Bold',
        borderWidth=1,
        borderColor=colors.HexColor('#eeeeee'),
        borderPadding=5
    )
    
    meta_style = ParagraphStyle(
        'MetaStyle',
        parent=styles['Normal'],
        fontSize=10,
        textColor=colors.HexColor('#666666'),
        alignment=TA_CENTER,
        spaceAfter=20
    )
    
    body_style = ParagraphStyle(
        'BodyStyle',
        parent=styles['BodyText'],
        fontSize=11,
        leading=16,
        alignment=TA_JUSTIFY,
        spaceAfter=10
    )
    
    disclaimer_style = ParagraphStyle(
        'DisclaimerStyle',
        parent=styles['BodyText'],
        fontSize=10,
        leading=14,
        alignment=TA_JUSTIFY,
        textColor=colors.HexColor('#856404'),
        backColor=colors.HexColor('#fff3cd'),
        borderWidth=1,
        borderColor=colors.HexColor('#f0ad4e'),
        borderPadding=10,
        leftIndent=10,
        rightIndent=10
    )
    
    footer_style = ParagraphStyle(
        'FooterStyle',
        parent=styles['Normal'],
        fontSize=9,
        textColor=colors.HexColor('#666666'),
        alignment=TA_CENTER,
        spaceAfter=5
    )
    
    # Build the document
    
    # Header
    elements.append(Paragraph("Mental Health Assessment Report", title_style))
    elements.append(Spacer(1, 0.1*inch))
    
    # Meta information
    session_id_short = session_data.session_id[:8] if len(session_data.session_id) > 8 else session_data.session_id
    meta_text = f"<b>Session ID:</b> {session_id_short} | <b>Date:</b> {datetime.now().strftime('%B %d, %Y')}"
    elements.append(Paragraph(meta_text, meta_style))
    
    # Add a horizontal line
    elements.append(Spacer(1, 0.2*inch))
    
    # Section 1: Personal Summary
    elements.append(Paragraph("Personal Summary", heading_style))
    elements.append(Spacer(1, 0.1*inch))
    elements.append(Paragraph(final_report.opening_summary, body_style))
    elements.append(Spacer(1, 0.2*inch))
    
    # Section 2: Assessment Results
    elements.append(Paragraph("Assessment Results", heading_style))
    elements.append(Spacer(1, 0.1*inch))
    elements.append(Paragraph(final_report.assessment_findings, body_style))
    elements.append(Spacer(1, 0.2*inch))
    
    # Section 3: Recommended Next Steps
    elements.append(Paragraph("Recommended Next Steps", heading_style))
    elements.append(Spacer(1, 0.1*inch))
    elements.append(Paragraph(final_report.recommended_steps, body_style))
    elements.append(Spacer(1, 0.2*inch))
    
    # Section 4: Important Disclaimer
    elements.append(Paragraph("Important Disclaimer", heading_style))
    elements.append(Spacer(1, 0.1*inch))
    elements.append(Paragraph(final_report.disclaimer, disclaimer_style))
    elements.append(Spacer(1, 0.3*inch))
    
    # Footer
    elements.append(Spacer(1, 0.2*inch))
    footer_text_1 = "This report is confidential and generated by Miraat Mental Health Assessment System."
    footer_text_2 = f"Report generated on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
    elements.append(Paragraph(footer_text_1, footer_style))
    elements.append(Paragraph(footer_text_2, footer_style))
    
    # Build the PDF
    doc.build(elements)
    
    # Get the PDF bytes from the buffer
    pdf_bytes = buffer.getvalue()
    buffer.close()
    
    return pdf_bytes