# app/services/pdf_report_service.py
import pdfkit
from datetime import datetime
from app.services.schemas import SessionData, FinalReport
import os

def generate_pdf_from_report(session_data: SessionData, final_report: FinalReport) -> bytes:
    """
    Takes the final SessionData and FinalReport and generates a PDF using wkhtmltopdf.
    Returns the PDF content as bytes.
    """
    try:
        # Generate HTML content
        html_content = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="UTF-8">
            <title>Miraat - Mental Health Report</title>
            <style>
                body {{ font-family: Arial, sans-serif; margin: 40px; line-height: 1.6; }}
                .header {{ text-align: center; margin-bottom: 30px; border-bottom: 2px solid #ccc; padding-bottom: 20px; }}
                .header h1 {{ color: #2c3e50; margin-bottom: 10px; }}
                .meta {{ color: #666; font-size: 14px; }}
                .section {{ margin: 25px 0; }}
                .section h2 {{ color: #2c3e50; border-bottom: 1px solid #eee; padding-bottom: 5px; }}
                .content {{ background: #f8f9fa; padding: 15px; border-left: 4px solid #10b981; margin: 10px 0; }}
                .disclaimer {{ background: #fff3cd; border-left-color: #f0ad4e; }}
                .footer {{ margin-top: 40px; padding-top: 20px; border-top: 1px solid #ccc; font-size: 12px; color: #666; }}
            </style>
        </head>
        <body>
            <div class="header">
                <h1>Mental Health Assessment Report</h1>
                <div class="meta">
                    <p><strong>Session ID:</strong> {session_data.session_id[:8]}</p>
                    <p><strong>Date:</strong> {datetime.now().strftime('%B %d, %Y')}</p>
                </div>
            </div>

            <div class="section">
                <h2>Personal Summary</h2>
                <div class="content">
                    <p>{final_report.opening_summary}</p>
                </div>
            </div>

            <div class="section">
                <h2>Assessment Results</h2>
                <div class="content">
                    <p>{final_report.assessment_findings}</p>
                </div>
            </div>

            <div class="section">
                <h2>Recommended Next Steps</h2>
                <div class="content">
                    <p>{final_report.recommended_steps}</p>
                </div>
            </div>

            <div class="section">
                <h2>Important Disclaimer</h2>
                <div class="content disclaimer">
                    <p>{final_report.disclaimer}</p>
                </div>
            </div>

            <div class="footer">
                <p>This report is confidential and generated by Miraat Mental Health Assessment System.</p>
                <p>Report generated on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
            </div>
        </body>
        </html>
        """

        # Configure PDF options
        options = {
            'page-size': 'A4',
            'margin-top': '0.75in',
            'margin-right': '0.75in',
            'margin-bottom': '0.75in',
            'margin-left': '0.75in',
            'encoding': "UTF-8",
            'no-outline': None
        }

        # Generate PDF from HTML
        pdf_bytes = pdfkit.from_string(html_content, False, options=options)
        return pdf_bytes

    except Exception as e:
        # Fallback: Return a simple text-based PDF if HTML conversion fails
        print(f"PDF generation failed: {e}")
        
        # Simple fallback using basic text
        simple_content = f"""
        MIRAAT MENTAL HEALTH REPORT
        
        Session ID: {session_data.session_id[:8]}
        Date: {datetime.now().strftime('%B %d, %Y')}
        
        PERSONAL SUMMARY:
        {final_report.opening_summary}
        
        ASSESSMENT RESULTS:
        {final_report.assessment_findings}
        
        RECOMMENDED NEXT STEPS:
        {final_report.recommended_steps}
        
        DISCLAIMER:
        {final_report.disclaimer}
        """
        
        # Return as plain text (browser will handle as download)
        return simple_content.encode('utf-8')